### ISSUE TITLE
LimeSDR support?

### ISSUE THREAD

**Issue by Redferne** [gasparka/spectrogram#10]
Tried to load this up on a standard LimeSDR, but I did not succeed. Is it supposed to work?

**Comment by gasparka** [comment]
Currently only LimeSDR-Mini is supported. I can't think of any benefit that would motivate the LimeSDR port. 

I will change the repo title to include 'LimeSDR-Mini' instead of just 'LimeSDR'.

**Comment by Redferne** [comment]
How do you mean 'motivate' a port? Is the functionality already available on the LimeSDR or would the work effort be too much?

**Comment by gasparka** [comment]
Too much work effort, because LimeSDR and LimeSDR-Mini have different FPGA images. Also, i consider LimeSDR a legacy device i.e. LimeSDR-Mini has new and better components e.g. FPGA and USB chip. It is unlikely that Lime will make new boards based on the LimeSDR design, in fact the new LimeNET-Micro is based on the Mini. That is what i mean by 'motivation'.
